# disable Stormpath's Spring Security support:
stormpath:
  spring:
    security:
      enabled: false
  web:
    login:
      enabled: true
      uri: "/login"
      view: "security/login"
    register:
      enabled: false
      uri: "/register"
      view: "security/register"
      
# disable Spring Security entirely:
security:
  basic:
    enabled: false